CAN C generator
joajfreitas/fcp-core pull request #107
Opened 2024-10-21 13:22 UTC by ItsNotSoftware

2024-10-23 18:15 UTC, ItsNotSoftware commented
Closes #103 
Closes #70

2024-10-24 13:59 UTC, joajfreitas requested changes
See the comments

2024-10-24 13:59 UTC, joajfreitas commented on plugins/fcp_can_c/templates/can_signal_parser.h
> +uint64_t can_decode_signal_as_uint64_t(const CanFrame *msg, uint64_t start,
We have to add more comprehensive tests for these files.

We can leave that for another PR.

2024-10-24 13:59 UTC, joajfreitas commented on src/fcp/specs/v2.py
> +
`get_matching_impls`

I've renamed `extension` to  `impl` following the syntax change. Anyway the protocol argument is not being used currently

2024-10-26 15:31 UTC, merged